apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: first-drones-routes
  namespace: default
spec:
  hosts:
  - dron1.default.svc.cluster.local
  http:
  - name: "version-routes"
    match:
    - uri:
        prefix: "/siemka"
    route:
    - destination:
        host: dron2.default.svc.cluster.local
        subset: dron2-service-subset
--- 

apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: dron1-destination
  namespace: default
spec:
  host: dron1.default.svc.cluster.local
  subsets:
  - name: dron1-service-subset
    labels:
      app: dron1
      version: v1

---

apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: dron2-destination
  namespace: default
spec:
  host: dron2.default.svc.cluster.local
  subsets:
  - name: dron2-service-subset
    labels:
      app: dron2
      version: v1
    