
# Copyright

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dron1
spec:
  selector:
    matchLabels:
      app: dron1
  template:
    metadata:
      labels:
        app: dron1
        version: 0.1.0-dron
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - name: server
        image: blazejczuk/drony:0.6
        ports:
        - containerPort: 3000
          name: http-dron1-svc
        envFrom:
        - configMapRef:
            name: special-config
        env:
        - name: NAME
          value: dron1
        - name: BG_COLOR
          value: blue
        - name: DRONES
          value: dron2,dron3,dron4
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dron2
spec:
  selector:
    matchLabels:
      app: dron2
  template:
    metadata:
      labels:
        app: dron2
        version: 0.1.0-dron
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - name: server
        image: blazejczuk/drony:0.6
        ports:
        - containerPort: 3000
          name: http-dron2-svc
        envFrom:
        - configMapRef:
            name: special-config
        env:
        - name: NAME
          value: dron2
        - name: BG_COLOR
          value: red
        - name: DRONES
          value: dron1,dron3,dron4
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dron3
spec:
  selector:
    matchLabels:
      app: dron3
  template:
    metadata:
      labels:
        app: dron3
        version: 0.1.0-dron
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - name: server
        image: blazejczuk/drony:0.6
        ports:
        - containerPort: 3000
          name: http-dron3-svc
        envFrom:
        - configMapRef:
            name: special-config
        env:
        - name: NAME
          value: dron3
        - name: BG_COLOR
          value: orange
        - name: DRONES
          value: dron1,dron2,dron4
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dron4
spec:
  selector:
    matchLabels:
      app: dron4
  template:
    metadata:
      labels:
        app: dron4
        version: 0.1.0-dron
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - name: server
        image: blazejczuk/drony:0.6
        ports:
        - containerPort: 3000
          name: http-dron4-svc
        envFrom:
        - configMapRef:
            name: special-config
        env:
        - name: NAME
          value: dron4
        - name: BG_COLOR
          value: green
        - name: DRONES
          value: dron1,dron2,dron3
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
