
# Copyright

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dron1
spec:
  selector:
    matchLabels:
      app: dron1
  template:
    metadata:
      labels:
        app: dron1
        version: 0.1.0-dron
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - name: server
        image: blazejczuk/drony:0.4
        ports:
        - containerPort: 3001
        env:
        - name: NAME
          value: dron1
        - name: BG_COLOR
          value: blue
        - name: DRONES
          value: dron2,dron3,dron4
        - name: DRONES_NUMBER
          value: ${DRONES_COUNT}
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi

---
apiVersion: v1
kind: Service
metadata:
  name: dron1
spec:
  type: ClusterIP
  selector:
    app: dron1
  ports:
    - protocol: TCP
      port: 3001

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dron2
spec:
  selector:
    matchLabels:
      app: dron2
  template:
    metadata:
      labels:
        app: dron2
        version: 0.1.0-dron
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - name: server
        image: blazejczuk/drony:0.4
        ports:
        - containerPort: 3001
        env:
        - name: NAME
          value: dron2
        - name: BG_COLOR
          value: red
        - name: DRONES
          value: dron1,dron3,dron4
        - name: DRONES_NUMBER
          value: ${DRONES_COUNT}
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi

---
apiVersion: v1
kind: Service
metadata:
  name: dron2
spec:
  type: ClusterIP
  selector:
    app: dron2
  ports:
    - protocol: TCP
      port: 3001

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dron3
spec:
  selector:
    matchLabels:
      app: dron3
  template:
    metadata:
      labels:
        app: dron3
        version: 0.1.0-dron
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - name: server
        image: blazejczuk/drony:0.4
        ports:
        - containerPort: 3001
        env:
        - name: NAME
          value: dron3
        - name: BG_COLOR
          value: orange
        - name: DRONES
          value: dron1,dron2,dron4
        - name: DRONES_NUMBER
          value: ${DRONES_COUNT}
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi

---
apiVersion: v1
kind: Service
metadata:
  name: dron3
spec:
  type: ClusterIP
  selector:
    app: dron3
  ports:
    - protocol: TCP
      port: 3001

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dron4
spec:
  selector:
    matchLabels:
      app: dron4
  template:
    metadata:
      labels:
        app: dron4
        version: 0.1.0-dron
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - name: server
        image: blazejczuk/drony:0.4
        ports:
        - containerPort: 3001
        env:
        - name: NAME
          value: dron4
        - name: BG_COLOR
          value: green
        - name: DRONES
          value: dron1,dron2,dron3
        - name: DRONES_NUMBER
          value: ${DRONES_COUNT}
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi

---
apiVersion: v1
kind: Service
metadata:
  name: dron4
spec:
  type: ClusterIP
  selector:
    app: dron4
  ports:
    - protocol: TCP
      port: 3001