---
apiVersion: v1
kind: Service
metadata:
  name: dron1
spec:
  type: ClusterIP
  selector:
    app: dron1
  ports:
    - name: http
      protocol: TCP
      port: 8081
      targetPort: http-dron1-svc
    
# kubectl -n default port-forward svc/dron1 8080

---
apiVersion: v1
kind: Service
metadata:
  name: dron2
spec:
  type: ClusterIP
  selector:
    app: dron2
  ports:
    - name: http
      protocol: TCP
      port: 8082
      targetPort: http-dron2-svc

# kubectl -n default port-forward svc/dron2 8081

---
apiVersion: v1
kind: Service
metadata:
  name: dron3
spec:
  type: ClusterIP
  selector:
    app: dron3
  ports:
    - name: http
      protocol: TCP
      port: 8083
      targetPort: http-dron3-svc

---
apiVersion: v1
kind: Service
metadata:
  name: dron4
spec:
  type: ClusterIP
  selector:
    app: dron4
  ports:
    - name: http
      protocol: TCP
      port: 8084
      targetPort: http-dron4-svc
